CREATE TABLE IF NOT EXISTS vk_user_group (
  id BIGSERIAL PRIMARY KEY,
  vk_group_id TEXT NOT NULL
  is_player BOOLEAN,
  vk_id BIGINT NOT NULL,
  CONSTRAINT fk_vk_id FOREIGN KEY (vk_id) REFERENCES player(vk_id) ON DELETE CASCADE
);